// templates/reactjs/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.less';

const sampleList = [
    'Create with React',
    'Build as Web Component',
    'Use it anywhere!',
];

export default function App() {

    return (<div className="wrapper">
        <span><img src={logo} alt=""/></span>
        <h3 className="info">Hello Freelog !</h3>
        {
            sampleList.map(sample => (<div key={sample}>{sample}</div>))
        }
    </div>);
}

// templates/vuejs/src/components/App.vue
<template>
    <div class="wrapper">
        <span>
            <img :src="logo" alt=""/></span>
        <h3 class="info">{{componentTitle}}</h3>
        <div v-for="sample in sampleList">{{sample}}</div>
    </div>
</template>

<script>
    import logo from '../assets/logo.svg';

    export default {
        name: 'App',
        data() {
            return {
                logo,
                componentTitle: 'Hello Freelog !',
                sampleList: [
                    'Create with React',
                    'Build as Web Component',
                    'Use it anywhere!',
                ]
            }
        },
        components: {
        }
    }
</script>
